[tools]
rojo = "rojo-rbx/rojo@7.6.0"
selene = "Kampfkarren/selene@0.27.1"
StyLua = "JohnnyMorganz/StyLua@0.20.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
